openapi: 3.0.0
info:
  title: Smart API Gateway
  description: API documentation for the Smart API Gateway project
  version: "1.0"
servers:
  - url: 'http://localhost:3000/api'
paths:
  /proxy:
    post:
      summary: Proxy request handler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                method:
                  type: string
                headers:
                  type: object
                body:
                  type: object
      responses:
        '200':
          description: Successfully proxied request
        '400':
          description: Bad request
        '500':
          description: Internal server error
