name: Deploy-Backend

on: 
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Deploy to Railway
        run: npx railway up --service=backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
